### ISSUE TITLE
DatabaseBranchPassword

### ISSUE THREAD

**Issue by cemo** [s1ntaxe770r/terraform-provider-planetscale#6]
Add resource for DatabaseBranchPassword please. I may take care myself too.

**Comment by cemo** [comment]
@[s1ntaxe770](https://github.com/s1ntaxe770r/terraform-provider-planetscale/commits?author=s1ntaxe770r)r
s1ntaxe770 would you please merge and cut a release? We are blocked now with this release.

**Comment by s1ntaxe770r** [comment]
Oof, I'm so sorry hold on.
